# Data Processing for glassy carbon (data-ingestion.py & dataset.py)
data:
  raw_dataset: "gc2.xyz"
  processed_xyz: "gc_filtered.xyz" 
  processed_pt: "gc_graph_data.pt"
  material_types: 
    - "amorphous"


# Graph Construction (dataset.py & diffusion.py)
graph:
  cutoff_radius: 5.0      # Ångströms
  max_neighbors: 12

# NequIP Model Architecture (nequip_layer.py)
model:
  num_layers: 3
  num_types: 1
  embedding_dim: 8
  bessel_basis: 8
  irreps_node: "64x0e + 32x1o"
  irreps_sh: "1x0e + 1x1o + 1x2e"
  irreps_edge: "4x0e + 4x1o + 2x2e"
  density_min: 1.4        # Minimum bound for scalar embedder gc2 = 1.5
  density_max: 1.6        # Maximum bound for scalar embedder

# DDPM Architecture (diffusion.py)
diffusion:
  num_steps: 3000
  sigma_min: 0.001
  sigma_max: 0.75
  langevin_steps: 2900    # Steps to apply extra noise during generation

# Training Hyperparameters (train.py)
training:
  batch_size: 2
  learning_rate: 0.0002   # 2e-4
  num_epochs: 40000           
  val_split: 0.1
  log_interval: 400
  checkpoints:
    latest: "gc_diffusion_latest.pt"
    best: "gc_diffusion_best.pt"
    final: "gc_diffusion_final.pt"
  loss_curve_img: "loss_curve.png"

# Inference & Generation (generate.py)
generation:
  target_density: 1.5
  cell_size: [14.21, 14.21, 14.21]
  num_atoms: 216
  output_filename: "generated_gc.xyz"

# Physics Evaluation (evaluate.py)
evaluation:
  tolerance: 0.05
  bins: 100
  output_img: "rdf_comparison.png"